### ISSUE TITLE
Issue on Windows OS

### ISSUE THREAD

**Issue by breisfeld** [n-riesco/ijavascript#28]
Hi,

On 20150519, I installed and ran IJavascript on Windows using

```
$ npm install -g ijavascript 

$ ijs
```

In the ipython log window, I get the following:

```
...
Error: Cannot find module 'C:\Program Files (x86)
odejs
ode_modules\ijavascript\lib\kernel.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
[W 07:08:35.098 NotebookApp] Timeout waiting for kernel_info reply from 578b1e81-6b59-42db-b993-7eb8d75092e7
[I 07:08:36.940 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 578b1e81-6b59-42db-b993-7eb8d75092e7 restarted
module.js:338
    throw err;
...
```

I am assuming that this is a path quoting issue on Windows. 

System details:

```
Windows 7
Python 2.7.8 |Anaconda 2.1.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1500 32 bit (Intel)]
IPython 3.1.0
node.js 0.12.0.
```

**Comment by n-riesco** [comment]
In the evening, I will try to set up IJavascript on a Windows machine and reproduce this bug.

In the meantime, please, could you post here the output of running:
```
$ node "C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js"
```
?

**Comment by breisfeld** [comment]
On 2015-05-19 8:32 AM, Nicolas Riesco wrote:
> |node "C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js"|

Thanks for the quick response.

$ node "C:\Program Files
(x86)\nodejs\node_modules\ijavascript\lib\kernel.js"
Usage: node kernel.js [--debug] session_working_directory
connection_file
C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js:79
    throw e;
          ^
Error: Error: missing session_working_directory
    at Object.<anonymous> (C:\Program Files
(x86)\nodejs\node_modules\ijavascript\lib\kernel.js:66:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by n-riesco** [comment]
It looks like you can run the IJavascript kernel from the command line, but not from IPython. I will investigate this further, once I setup IJavascript on a Windows machine.

**Comment by n-riesco** [comment]
Hi! I couldn't reproduce the same error message, but I found a bug building the path to the kernel folder. I've just released version 5.0.1 that fixes this bug. Please, could you install IJavascript again and check whether this release fixes the issue for you?

**Comment by breisfeld** [comment]
I just did a 

```
$ npm install ijavascript

$ ijs
```

I am getting the same issue as before:

```
Error: Cannot find module 'C:\Program Files (x86)
odejs
ode_modules\ijavascript\lib\kernel.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
[W 05:55:14.108 NotebookApp] Timeout waiting for kernel_info reply from 6e44ac95-789b-4636-a3ee-797035bbffb6
[I 05:55:15.936 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 6e44ac95-789b-4636-a3ee-797035bbffb6 restarted
module.js:338
    throw err;
```

Running outside of ```ijs```, I get

```
$ node "C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js"
Usage: node kernel.js [--debug] session_working_directory connection_file
C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js:79
    throw e;
          ^
Error: Error: missing session_working_directory
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\ijavascript\lib\kernel.js:66:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by n-riesco** [comment]
The install command is missing `-g`. Please, try:
```
$ npm install -g ijavascript
```
And to confirm that version 5.0.1 is globally installed, try:
```
$ npm list -g ijavascript
```
It should show version 5.0.1

**Comment by breisfeld** [comment]
As indicated above, I did ```install``` ijavascript, though not globally.

I just used the exact commands you listed above and confirmed that I am indeed using v5.0.1.

Unfortunately, the problem persists. 

The following line in the console output is very odd:
 
```
Error: Cannot find module 'C:\Program Files (x86)
odejs
ode_modules\ijavascript\lib\kernel.js'
```

It looks like the path is not being interpreted correctly. As I mentioned initially, could this be a quoting issue?

**Comment by n-riesco** [comment]
Oh! So the path is actually printed out broken like that?

Could you check for me if the path in the kernel spec file is also broken?
If you run:
```
$ ipython locate
```
It should print the IPython folder. Let's say it prints "C:\Users\breisfeld\.ipython". Then, the kernel spec should be located in "C:\Users\breisfeld\.ipython\kernels\javascript\kernel.json".

**Comment by breisfeld** [comment]
This does appear to be broken.

My ipython preferences directory is something like

"C:\Users\USERNAME\AppData\Roaming\.ipython"

Within this directory, I do have a "kernels" subdirectory. It does contains other kernels I have installed (e.g., julia), but not the one for javascript.

I can't find any "...\javascript\kernel.json" on my machine.

**Comment by n-riesco** [comment]
Just to be clear, when you run `ipython locate`, what you get is "C:\Users\USERNAME\AppData\Roaming.ipython", isn't it?

**Comment by n-riesco** [comment]
And one more question: I've noticed you're using IPython 3.1.0, whereas Anaconda 2.1.0 provides IPython 2.2.0. How did you upgrade IPython?

**Comment by breisfeld** [comment]
```
$ ipython locate
C:\Users\USERNAME\AppData\Roaming\.ipython
```

To update ipython, I believe that I downloaded the wheel from Christoph Gohlke's "Unofficial Windows Binaries for Python Extension Packages" site (http://www.lfd.uci.edu/~gohlke/pythonlibs/) and installed that using 

```
pip install ipython‑3.1.0‑py27‑none‑any.whl
```

**Comment by n-riesco** [comment]
And when you run `ipython --version` from the terminal, what do you get 3.1.0 or 2.2.0?

**Comment by breisfeld** [comment]
```
$ ipython --version
3.1.0
```

**Comment by n-riesco** [comment]
I've just updated IJavascript (v5.0.2). Please, could you install IJavascript again, run the following command and post the output here:
```
$ ijs --ijs-debug --ijs-install-kernel
```
?

I hope it'll give me a clue to locate the bug.

**Comment by breisfeld** [comment]
```
$ ijs --ijs-debug --ijs-install-kernel
Error: Unrecognised flag '--ijs-install-kernel'

iJavascript Notebook

Usage:

    ijs <options>

The recognised options are:

    --ijs-debug             enable debug log level
    --ijs-help              show this help
    --ijs-working-dir=path  set working directory for Javascript sessions
                            (default = current working directory)

and any other options recognised by the IPython notebook; run:

    ipython notebook --help

for a full list.
```

**Comment by n-riesco** [comment]
That output indicates that the IJavascript in your system is version v5.0.0 or earlier.

The easiest way to run IJavascript is when IJavascript has been installed globally:
```
$ npm install -g ijavascript
$ ijs --ijs-debug --ijs-install-kernel
```
If you want to install it locally, then running IJavascript requires to include the right path to the local installation:
```
$ npm install ijavascript
ijavascript@5.0.2 ../node_modules/ijavascript
├── jmp@0.0.6
├── node-uuid@1.4.3
└── zmq@2.11.1 (bindings@1.1.1, nan@1.8.4)
$ ../node_modules/.bin/ijs --ijs-debug --ijs-install-kernel
```

**Comment by breisfeld** [comment]
Okay. I think I have this working. 

I ended up removing my previous ijavascript installations (I had a global and local one) and installed the latest version globally via npm.

Thank you for your help!

**Comment by n-riesco** [comment]
Does the latest version work for you? Shall I close this bug?

**Comment by breisfeld** [comment]
Yes and yes.
